services:
  - type: web
    name: ideasapp
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: ideasapp-disk
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1 